import {
  Play,
  Download,
  Share,
  Bookmark,
  FolderPlus,
  Plus,
  Maximize2,
  Minimize2,
  X as Close,
  ChevronDown,
  ChevronUp,
  Settings,
  Database,
  FileText,
  Info,
  Cloud,
  HelpCircle,
  Code,
  Search,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Trash,
  Edit,
  Copy,
  ExternalLink,
  ChevronDown as Down,
  ChevronUp as Up,
  Pin,
  Loader
} from 'lucide-react'

// Common icon props
const defaultProps = {
  size: 16,
  className: 'text-current'
}

export const Icons = {
  Play: (props: any) => <Play {...defaultProps} {...props} />,
  Download: (props: any) => <Download {...defaultProps} {...props} />,
  Share: (props: any) => <Share {...defaultProps} {...props} />,
  Bookmark: (props: any) => <Bookmark {...defaultProps} {...props} />,
  FolderPlus: (props: any) => <FolderPlus {...defaultProps} {...props} />,
  Plus: (props: any) => <Plus {...defaultProps} {...props} />,
  Maximize: (props: any) => <Maximize2 {...defaultProps} {...props} />,
  Minimize: (props: any) => <Minimize2 {...defaultProps} {...props} />,
  Close: (props: any) => <Close {...defaultProps} {...props} />,
  ChevronDown: (props: any) => <ChevronDown {...defaultProps} {...props} />,
  ChevronUp: (props: any) => <ChevronUp {...defaultProps} {...props} />,
  Settings: (props: any) => <Settings {...defaultProps} {...props} />,
  Database: (props: any) => <Database {...defaultProps} {...props} />,
  FileText: (props: any) => <FileText {...defaultProps} {...props} />,
  Info: (props: any) => <Info {...defaultProps} {...props} />,
  Cloud: (props: any) => <Cloud {...defaultProps} {...props} />,
  Help: (props: any) => <HelpCircle {...defaultProps} {...props} />,
  Code: (props: any) => <Code {...defaultProps} {...props} />,
  Search: (props: any) => <Search {...defaultProps} {...props} />,
  Warning: (props: any) => <AlertTriangle {...defaultProps} {...props} />,
  Success: (props: any) => <CheckCircle {...defaultProps} {...props} />,
  Error: (props: any) => <XCircle {...defaultProps} {...props} />,
  Delete: (props: any) => <Trash {...defaultProps} {...props} />,
  Edit: (props: any) => <Edit {...defaultProps} {...props} />,
  Copy: (props: any) => <Copy {...defaultProps} {...props} />,
  External: (props: any) => <ExternalLink {...defaultProps} {...props} />,
  Down: (props: any) => <Down {...defaultProps} {...props} />,
  Up: (props: any) => <Up {...defaultProps} {...props} />,
  Pin: (props: any) => <Pin {...defaultProps} {...props} />,
  Loader: (props: any) => <Loader {...defaultProps} {...props} />
} 