export const USER_COMMAND_QUEUED = 'editor/USER_COMMAND_QUEUED'
export const ADD_HISTORY = 'editor/ADD_HISTORY'
export const SET_MAX_HISTORY = 'editor/SET_MAX_HISTORY'
export const SET_CONTENT = 'editor/SET_CONTENT'
export const ADD_FAVORITE = 'editor/ADD_FAVORITE'
