ui: mocha-bdd
tunnel:
  type: ngrok
  authtoken: 5P5swTMSDDRlnMBkBWJt
  proto: https
scripts:
  - "/test/support/config.js"
  - "/node_modules/expect.js/expect.js"
  - "/node_modules/sinon/pkg/sinon-1.14.1.js"
  - "/build/auth0.js"
browsers:
  - name: chrome
    version: 27..latest
  - name: safari
    version: latest
  - name: firefox
    version: 28..latest
  - name: ie
    version: 8..latest
