/*
 * Copyright (c) 2002-2020 "Neo4j,"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React from 'react'
import { render } from '@testing-library/react'
import MdxSlide from './MdxSlide'

describe('MdxSlide', () => {
  beforeAll(() => {
    // Error Boundary prints mdx parse errors to console, this mock is to not clutter test output
    jest.spyOn(console, 'error').mockImplementation(() => {})
  })

  afterAll(() => {
    console.error.mockRestore()
  })

  it('retains standard markup generated by markdown', () => {
    const mdx = '# Title'

    const { container } = render(<MdxSlide mdx={mdx} />)

    expect(container.querySelector('h1').textContent).toEqual('Title')
  })

  it('renders an error message when mdx contains syntax errors', () => {
    const mdx = `<d
    iv>asdf</div>`

    const { container } = render(<MdxSlide mdx={mdx} />)

    expect(container.querySelector('pre').textContent).toEqual(
      'Error: closing tag must match opening tag name!'
    )
  })

  it('renders an error message when jsx js expression contains any non-literal', () => {
    const mdx = `<div>{alert('foo')}</div>`

    const { container } = render(<MdxSlide mdx={mdx} />)

    expect(container.querySelector('pre').textContent).toContain(
      `Unexpected plaintext token: "alert('foo')"`
    )
  })

  it('renders an error message when jsx contains event listeners', () => {
    const mdx = `<h1 onClick={"foo"}>bar</h1>`

    const { container } = render(<MdxSlide mdx={mdx} />)

    expect(container.querySelector('pre').textContent).toEqual(
      `Event binder onClick found in h1`
    )
  })
})
