/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
import { render, screen } from '@testing-library/react'
import React from 'react'

import MdSlide from './MdSlide'

describe('MdSlide', () => {
  it('retains standard markup generated by markdown', () => {
    const md = '# Title'

    const { container } = render(<MdSlide md={md} />)

    expect(
      (container.querySelector('h1') as HTMLHeadingElement).textContent
    ).toEqual('Title')
  })

  it('handles real life markdown', () => {
    const md = `# Network Analysis of Shakespeare's plays
![William Shakespeare](https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTE1ODA0OTcxNzgzMzkwNzMz/william-shakespeare-194895-1-402.jpg)

## Finding a Data source
That was so easy. I very quickly located a [Dataset on Kaggle](https://www.kaggle.com/kingburrito666/shakespeare-plays) that I thought would be really interesting. It's a comma-separated file, about 110k lines long and 10MB in size, that holds all the lines that Shakespeare wrote for his plays. It's just an amazing dataset - not too complicated, but terribly interesting. 

The structure of the file has the following _File headers_: 

|Dataline|Play|PlayerLinenumber|ActSceneLine|Player|PlayerLine|
|---|---|---|---|---|---|
|abc|def|ghi|jkl|mno|pqr|

Of course you can find the dataset on Kaggle yourself, but I actually quickly imported it into a [google sheet version](https://secret.com) that you can access as well. This gsheet is shared and made public on the internet, and can then be [downloaded as a csv at any time from this URL](https://docs.google.com/spreadsheets/d/15c6eUbRMNDrPa0RTuzdrY46OAr2FzKH8tD0KZNoaG8c/export?format=csv&gid=1470339152). This URL is what we will use for importing this data into Neo4j.

So let's see how we can do that.
    
---
    
## Prepare the database
Assuming that you are using one of the latest versions of Neo4j, which supports multiple databases, you should start by creating the database for this exercise:
    
\`\`\`cypher
:use system;
create or replace database shakespeare;
:use shakespeare;
\`\`\`

Once that is done, you should also create some indexes on the database, as that will help with the data import and querying later on:

\`\`\`cypher
create index on :Play(name);
create index on :Player(name);
create index on :Scene(name);
create index on :Act(name);
create index on :Line(PlayerLine);
create index on :Line(Dataline);
create index on :Line(Play);
create index on :Line(Act);
create index on :Line(Scene);
\`\`\``

    const { container } = render(<MdSlide md={md} />)

    expect(screen.getByRole('heading', { level: 1 }).textContent).toEqual(
      `Network Analysis of Shakespeare's plays`
    )

    expect(screen.getAllByRole('img')[0]).toHaveAttribute(
      'src',
      'https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTE1ODA0OTcxNzgzMzkwNzMz/william-shakespeare-194895-1-402.jpg'
    )
    expect(screen.getAllByRole('link')[0]).toHaveAttribute(
      'href',
      'https://www.kaggle.com/kingburrito666/shakespeare-plays'
    )
    // Make code blocks are clickable
    expect(container.getElementsByTagName('pre')[0]).toHaveClass('runnable')
  })
})
