export const ADD = 'datasource/ADD'
export const REMOVE = 'datasource/REMOVE'
export const DID_RUN = 'datasource/DID_RUN'
export const DID_FAIL = 'datasource/DID_FAIL'
export const UPDATE = 'datasource/UPDATE'
export const COMMAND_QUEUED = 'datasource/COMMAND_QUEUED'
