[[visual-tour]]
= Visual tour

[abstract]
--
This chapter presents a visual overview of the UI of Neo4j Browser.
--


// https://neo4j.com/docs/bloom-user-guide/current/bloom-visual-tour/#visual-tour
// https://medium.com/neo4j/neo4j-browser-embraces-the-monaco-editor-bc8415cac22e
// https://medium.com/neo4j/wheres-my-neo4j-cypher-query-results-%EF%B8%8F-%EF%B8%8F-9c3b150e6e19

[[overview]]
== Overview

//Add a screenshot similar to https://neo4j.com/docs/bloom-user-guide/current/_images/visual-tour.png

=== The sidebar

The sidebar contains a set of drawers where you can set up the environment for graph management and exploration.

* Browser Settings - provides Browser settings.
* About Neo4j - shows the Neo4j Browser version, license information, and provides a link to a link to Neo4j Browser Changelog.
* Browser Sync - allows you to synchronize your favorites, styling, and settings to cloud storage, so you can share it across machines and browsers.
* Help and Learn - contains useful commands, built-in guides, links to documentation, notifications, and a send feedback button.
// https://miro.medium.com/max/680/1*qMw6LTOZNErrdvUO7XUSpQ.png
//   Commands
//   Guides
//   Links to documentation
//   Canny: Send feedback
//   Notification Bell, Canny: Latest Updates
* Favorites - allows you to bookmark your queries as favorites.
//https://miro.medium.com/max/1400/0*WxSIQfG5d3alMsd6.png
//   Local scripts
//   Sample scripts
* Database Information - contains information about the currently used node labels, relationship types, and property keys. +
Clicking on any one of those options runs a quick query to show you a sample of the graph with those elements.

//TODO: To write a short paragraph about each of the drawers using https://neo4j.com/developer/neo4j-browser/.

[[editor]]
== Cypher editor

The Cypher editor is the primary interface for entering and running commands.

* Cypher queries to work with graph data.
* Client-side commands like `:help` for other operations.
* REST request commands (`:GET`, `:POST`, `:PUT`, and `:DELETE`).
* Single line editing for brief queries or commands.
* Switch to multi-line editing with *<Shift-Enter>*.
* Run a query with *<Ctrl-Enter>* or *<Cmd-Enter>*.
* History is kept for easily retrieving previous commands.
* Autocomplete for browser commands.
* Move focus to the editor with /.
* Toggle the editor to full screen with ESC.

Use the command `:help keys` for information about keyboard shortcuts.

The Cypher editor in Neo4j Browser 4.2.4 is based on Monaco link:https://microsoft.github.io/monaco-editor/[https://microsoft.github.io/monaco-editor/], the editor that powers VS Code link:https://github.com/Microsoft/vscode[https://github.com/Microsoft/vscode].

// https://neo4j.com/developer-blog/neo4j-browser-embraces-the-monaco-editor/
// https://browser.graphapp.io/assets/images/screen_editor.png

[[frames]]
== Result frames

=== Stream

// https://browser.graphapp.io/assets/images/screen_stream.png

Scrolling series of frames (mostly reusable result frames).

A reusable result frame is created for each command execution, added to the top of the stream to create a scrollable collection in reverse chronological order.

Remove all the frames from the stream with the :clear command.

=== Reusable result frames

// https://miro.medium.com/max/1280/0*DmPXwO3Q_hyunN3I.gif

Cells with results that you can reiterate on.

Now, when you need to edit the query of an existing result frame to fix a mistake, you can do that directly in the result frame and update the results in situ.

The reusable frame maintains its own local history of commands as well as updating the main Cypher editor, should you need to instantiate a new result frame from there.

//https://miro.medium.com/max/640/0*DmPXwO3Q_hyunN3I.gif[(Fullscreen) inline result frame editor]

Result frame views:

* Graph - Display the result as nodes and relationships. Styling can be configured.
* Table - Display the result as JSON formatted rows.
* Text - Display the result as a plain text table.
* Code https://browser.graphapp.io/assets/images/screen_code_frame.png - View the requests and responses.

[[guides]]
== Browser guides

Neo4j Browser provides many interactive guides for learning concepts and tools with Neo4j.
From data import to graph algorithms to working with RDF data, there is likely an interactive browser guide out there to walk through it.
If there is not one that fits your needs, you can create one and publish it to the community or internally at your company.
For more information on how to do that, see link:https://neo4j.com/developer/guide-create-neo4j-browser-guide/[creating a custom Browser guide].

=== Built-in guides

Some guides ship with Neo4j Browser out-of-the-box, no matter what system or installation you are working on.
The Browser built-in guides are quick guides that introduce different Neo4j concepts.
You can find more helpful links in the left sidebar of Neo4j in the "Documents" tab ().
To pin a particular pane to the top of the window (under command line) so that it stays at the top when you run queries after it, just click the pushpin button ().
This is especially helpful for pinning guides to the top so they do not get pushed down to the bottom of the window as you run queries.

.Built-in guides and commands
[cols="<,<", options="header"]
|===
| Guide command
| Description

| `:play intro`
| Neo4j Browser User Interface

| `:play concepts`
| Basic property-graph concepts to get you going

| `:play learn`
| Learn (Graph database fundamentals)

| `:play cypher`
| Cypher basics - create, match, patterns

| `:play movie graph`
| The Movie Graph, a mini graph model of connections between actors and movies

| `:play northwind graph`
| The Northwind Database, a classic use case of RDBMS to graph with import instructions and queries

|`:play start`
| Getting started with Neo4j Browser - concepts, write-code, system info

| `:play write-code`
| Jump right into coding with example data graphs (Shows both guides for movie graph and northwind graph)

| `:play fabric`
| The basics of setting up and using Neo4j Fabric.

| `:play`
| Use `:play <url>` to play a custom guide.
For more information on how to create a custom Browser guide, see link:https://neo4j.com/developer/guide-create-neo4j-browser-guide/[https://neo4j.com/developer/guide-create-neo4j-browser-guide/]
|===

All you have to do is enter any of the above commands in the Browser command line (at the top of the pane) and follow the accompanying guides to walk through the training or scenarios.
Guides are presented as slideshows that can be navigated by clicking the forward and back arrows in the pane to progress to the next or previous slide.
To execute any of the queries provided within a Browser guide, simply click on the query, and it will populate in the command line.
Then, just press *Enter* or the *Play* button to execute the statement.
Results of the query populate in a panel right below the command line.

=== Public Guides

Other guides are created by Neo4j staff and community members to help others learn Neo4j or how to use the tools in its ecosystem.

You can check out the currently published list on the link:https://portal.graphgist.org/graph_guides[GraphGist Portal (Graph Guides section)].

=== Create a custom guide

You can create a custom Browser guide and publish it to the community or internally at your company.
For more information on how to do that, see link:https://neo4j.com/developer/guide-create-neo4j-browser-guide/[creating a custom Browser guide].


// Links to the guides' source:
//======
// guided experience - https://github.com/neo4j/neo4j-browser/tree/master/src/browser/documentation/guides
//
// Getting started with Neo4j Browser (Neo4j Browser user interface guide) - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/start.tsx
// Basic concepts to get you going - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/concepts.tsx
// Cypher - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/cypher.tsx
// Icons (A mostly UI-focused subset of Streamline icons.) - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/iconography.tsx
// Intro( Neo4j Browser User Interface) - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/intro.tsx
// Learn (Graph database fundamentals.) - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/learn.tsx
// Typography (The typography is pleasantly minimal. Just enough to make for easy reading of brief content.) - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/typography.tsx
// Write code (Jump right into coding with example data graphs) - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/write-code.tsx
// Fabric - https://github.com/neo-technology/neo4j-manual-modeling/blob/4.3/operationsManual/asciidoc/tutorial/fabric-browser-guide.adoc
// Graph Examples:
// Movie Graph - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/movie-graph.tsx
// Northwind Graph - https://github.com/neo4j/neo4j-browser/blob/master/src/browser/documentation/guides/northwind-graph.tsx
//

[[favorites]]
== Favorites and saved files

// https://miro.medium.com/max/1400/0*WxSIQfG5d3alMsd6.png

Favorites are used to save scripts (Cypher queries and commands) to be easily reused.
Favorites can be organized into folders.

. Create or update your favorites.
. Create a new empty favorite.
. Individual favorite changes.
. Bulk favorite changes.

There are local scripts and sample scripts.

The name of the script is the first line of the script.
To control the name use a comment as the first line.

The example shows a script that will have the name likes candy in favorites.

.Favorite: Likes candy
====
[source, cypher]
----
//likes candy
MATCH (n)-[:LIKES]->(:Candy)
RETURN n AS node
----
====

// TODO: difference between favorites and saved files
//
// https://neo4j.com/developer/neo4j-browser/#browser-favorites
// https://neo4j.com/developer/neo4j-browser/#browser-styling-adv
// https://neo4j.com/developer/kb/how-do-i-export-cypher-favorites-recorded-in-the-browser/


[[settings]]
== Settings

// https://neo4j.com/developer/neo4j-browser/#browser-config
// https://neo4j.com/developer/kb/how-do-i-override-browser-configuration-settings/

Uncheck the `Connect result nodes` in settings, to remove automatically query and show relationships.
