name: 'Browser PR unit tests'

on:
  pull_request:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm -g install yarn
      - run: yarn install --frozen-lockfile
      - name: run unit tests
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
        run: yarn test
