name: "Test @neo4j-devtools/arc"

defaults:
  run:
    working-directory: src/neo4j-arc

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm -g install yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
