name: 'Arc PR e2e tests'

defaults:
  run:
    working-directory: src/neo4j-arc

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm -g install yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
